Android/Overview.txt
Add overview for the Android Folder
=> Add overview for Android folder

Algorithms/Dynamic Programming/LongestAlternatingSubsequence, Algorithms/Searching/Binary Search
A binary search algorithm to check whether an element is present in the array
=> Create Binary Search

Data Structures/LinkedLists.c
Add the basic impl of LinkedList
=> Add linkedlist data structure

Breadth First Search.txt, Depth First Search.txt, Kadane Algorithm.txt, Krushals Min Cost Spanning Tree.txt, Prefix Sum Algorithm.txt, Prim Min Spanning Tree.txt
1.  Kadane Algorithm is used to find the sum of contiguous subarray within a one-dimensional array of numbers which has the largest sum.
2. Prefix Sum Algorithm - Given an array arr[] of size n, its prefix sum array is another array prefixSum[] of same size such that the value of prefixSum[i] is arr[0] + arr[1] + arr[2] … arr[i].
=> Kadane and Prefix Sum Algorithm

AVL TREES.txt, Algorithms/AVL TREES.txt, Algorithms/Disjoint sets.txt, Data Structures/Heap/Create Heap Using STL Vector.txt, Data Structures/Heap/Heap Sort.txt, Data Structures/Heap/Heapify_Faster_Method_to_CreateHeap_C++.txt, Tower of Hanoi Recursion.txt
Heap 
Disjoint sets
Avl trees
Tower of hanoi
=> Heap ,Disjoint sets, Avl trees, Tower of hanoi

Android/recyclerViewAdapter.kt, Android/rvItemAnimator.kt
- Use Kotlin 
- Ability to provide interfaces for on click functionalities
- Can make use of custom data also
=> Add template for custom Recycler View Adapter

Data Structures/Merge Sort/Merge Sort.cpp
**Added Merge Sort Algorithm Code in C++**
Details:
Time Complexity : O(n * log(n)) Space Complexity : O(n)
where n is size of input array
I am a participant of **Hacktoberfest 2021**. Kindly review and merge this branch or **please label it as 'hacktoberfest-accepted'** . Thank You !!
=> Added Merge Sort.cpp

Algorithms/Sorting Algorithms/Insertion_Sort.java
I am a participant of Hacktoberfest 2021.  Can you please review my PR.  Thank You !!
=> Added Insertion sort in java

Algorithms/Searching/frequencyOf1.cpp
This is a program to find the frequency of 1 in sorted array consist of only 0 and 1 as elements.This is the optimized code using binary search algorithm.
=> program to find the frequency of 1 in sorted array of 0 and 1

Data Structures/LinkedList/Delete a Linked List
This code is about how you delete a linked list.
=> Deleting a node from a Linked List

Algorithms/2Pointer Algorithm/pairSum.cpp
PROGRAM TO FIND IF THERE EXIST ANY PAIR OF ELEMENTS SUCH THAT THEIR SUM IS 
EQUAL TO x IN SORTED ARRAY.
=> pair sum in sorted array

Android/initNavDrawer.kt
Android Material Navigation Drawer Initialization in .kt class file
=> Android Material Navigation Drawer Initialization

Competitive programming template/template.cpp, Competitive programming template/template.kt
I have added templates in kotlin and c++ , for debugging code easily.
=> Templates for competitive programming

Algorithms/Searching/LinearSearch.cpp
added linear search program into algorithms searching directory
=> Add Linear Search Program With Description

Algorithms/Searching/maximumInBitonic.cpp
A bitonic array is an array which first increase then decrease
=> program to find maximum element in bitonic array

Web development/JS/asyncawait.js
Please review under web development and file asyncawait.js
=> webdevelopment - js asyncawait.js

Project/Python/audio_translate.py
Initialized project folder with one python program.
=> Python Program to convert audio into text

Algorithms/Sorting Algorithms/daa_topological sorting.cpp
Added topological sort program
=> Added topological sort program

CONTRIBUTING.md
- Added `contributing.md` to the project
Fixes #62
=> qa : Added contributing.md to the project

.github/PULL_REQUEST_TEMPLATE.md
- qa : Added `PR template` to the project
Fixes #63
=> qa : Added PR template to the project

CODE_OF_CONDUCT.md
-  Added Code of conduct to the project
Fixes #65
=> qa : Added Code of conduct to the project

README.md
- docs : Readme Improved
Fixes #64
=> docs : Readme Improved

Data Structures/Array/Peak_element.cpp
Added CPP Program for finding Peak Element in an array
=> Added CPP Program for finding Peak Element in an array

Data Structures/Recursion/generating_subset_string.cpp, Data Structures/Recursion/rope_cutting.cpp, Data Structures/Recursion/tower_of_hanoi.cpp, Data Structures/Tree/Left_view_print.cpp, Data Structures/Tree/Level_order_traversal_line_by_line.cpp
=> Created a cpp file left_view_print.cpp

Data Structures/Tree/Check_balanced.cpp, Data Structures/Tree/Max_Width_of_bt.cpp
=> Created a file Max_Width_of_bt.cpp

Algorithms/Sorting Algorithms/heapSort.cpp, Algorithms/Sorting Algorithms/mergeSort.cpp, Algorithms/Sorting Algorithms/quickSort.cpp
Added merge sort, quick sort and heap sort in sorting algorithms. This is a part of my hacktoberfest contributions.
=> Added merge, quick and heap sort in Sorting Algorithms

README.md
Remove the hacktoberfest banner representative of Year 2021
=> fix: Update README.md for 2022

Web development/Website Project/index.html, Web development/Website Project/style.css
Footer issue solved + made footer responsive
Fixes #192
=> Footer issue solved + made footer responsive

C Language/Calculator.c
=> Added calculator program

Python/Countodown timer in python
=> Create Countodown timer in python

Web development/notes_app/app.js, Web development/notes_app/index.html, Web development/notes_app/todo.css
=> Notes App UI Updated

C Language/Bank_Management_System.c
=> Bank Management System Added

C Language/Kadane’s_Algorithm.c
=> Added Kadane's Algorithm.c

C Language/Queue_Using_Array.c
=> Queue Program Added

Java/PasswordGenerator.java
I have added a java program that generate password.
- [x ] New feature (non-breaking change which adds functionality)
- [ x] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [x ] My changes generate no new warnings.
=> Added PasswordGenerator.java

Algorithms/Sorting Algorithms/java/RadixSort.java
=> Radix Sort implementation in java

Algorithms/Sorting Algorithms/python/bubble_sort.py
=> added the code of bubble sort in python

Algorithms/Arrays -  Left Rotation.cpp, Algorithms/Arrays - 2D Array - DS.cpp, Algorithms/Arrays - Array Manipulation.cpp, Algorithms/Arrays - Minimum Swaps 2.cpp
=> Hackerrank - Hacktoberfest

Algorithms/Dynamic Programming/dice_combination.cpp
Added Dice Combination problem solved using DP in cpp language.
=> Dice Combination DP problem

C Language/multiplication_table.c
=> Create new program

Java/CountPairsWithGivenSum.java
Added a code snippet to calculate the pairs in an array with a given sum. Have also highlighted the space and time complexities along with the description.
=> Added code snippet to compute pairs with given sum

Artificial Intelligence/Informed Search/A Star/astar.py, Artificial Intelligence/Informed Search/A Star/heuristics.py, Artificial Intelligence/Informed Search/A Star/main.py
Added algorithm for Informed Search- A Star in the Artificial Intelligence directory.
Directory of new/updated file: "Artificial Intelligence"
=> informed search-astar

Algorithms/Searching/InsertionSort.java
I have added insertion sort, implemented in java. Please add "Hacktoberfest-Accepted" label.
Thank you
=> insertion sort in java

Python/DSAinpy/DoublyLinkedList.py, Python/DSAinpy/SinglyLinkedList.py, Python/DSAinpy/ddl2bst.py, Python/DSAinpy/merge.py, Python/DSAinpy/mergedetect.py, Python/DSAinpy/stack.py
Added new python DSA codes in the python folder.
=> Added some DSA in the python folder

Python/KL_Divergence.py
Function to calculate kl divergence.
Directory of new/updated file: "Python"
=> KL Divergence

Algorithms/Sorting Algorithms/python/RadixSort.py
=> Radix Sort Implementation in Python

Data Structures/Radix_sort
=> added radix sort

Data Structures/quicksort
=>  added quicksort

Kadane’s Algorithm
=> Create Kadane’s Algorithm

Algorithms/Searching/LinearSearch.java
<br>
Directory of new/updated file: "LinearSearch.java"
=> Added LinearSearch.java

Algorithms/Searching/LinearSearch.java, Data Structures/Array/ReverseArray.java
<br>
Directory of new/updated file: "ReverseArray.java"
=> Added ReverseArray.java

Data Structures/Binary Trees/Binary Tree Level Order Traversal.cpp
=> Create Binary Tree Level Order Traversal.cpp

Algorithms/Sorting Algorithms/python/CountingSort.py
=> Counting Sort Implementation in Python

Algorithms/Sorting Algorithms/cpp/topological sorting.cpp
=> added topological sorting

Data Structures/Binary Trees/inorder_traversal.cpp
=> added a new snippet in binary trees

Android/ToDo List App/MainActivity.java, Android/ToDo List App/activity_main.xml
Added java source code of ToDo List Android app along with its layout design in .XML.
Fixes #254
<br>
Directory of new/updated file: "Snippets\Android\ToDo List App\MainActivity.java"
=> ToDo List Android App Source Code added

Cryptography Algorithms/DiffieHellman.java, Cryptography Algorithms/PlayfairCipher.java, Cryptography Algorithms/RSA.java, Cryptography Algorithms/RailFenceCipher.java, Cryptography Algorithms/VigenereCipher.java, Python/Notepad.py
Added Cryptograpgy directory containing algorithms written in Java 
Fixes #253 
<br>
Directory of new/updated file: "Snippets\Cryptography Algorithms"
=> Cryptography codes

Python/Notepad.py
Added a Notepad App developed using Python GUI library Tkinter
<br>
Directory of new/updated file: "Snippets\Python\Notepad.py"
=> Added Notepad app based python GUI Tkinter

Algorithms/Knapsack-Greedy.java
=> Adding knapsack-greedy.java

Algorithms/12_IntegerToRoman.cpp
Fixes #250  
<br>
Directory of new/updated file: "/Algorithm/"
=> Added code for issue #250

Java/Quick_sort.java, Java/Radix_sort.java
I Have added Quick sort & Radix sort in java folder
Fixes - The java folder didnt have sorting codes , hereby added it
Please do approve PR
=> Added Quick_sort & Radix_sort in Java

Data Structures/Recursion/DFS_number _of_islands.cpp
Added a popular DFS(Depth first Search) question which helps us understand the different concept of Recursion and helps in implementing it to the other problems too !
=> number_of_islands

Web development/Temperature Calculator/index.html, Web development/Temperature Calculator/script.js, Web development/Temperature Calculator/style.css
I add Temperature Converter in Web Development folder of this repo.
<br>
Directory of new/updated file: "web development/Temperature Converter"
=> Temperature Converter Added in Web Development Folder

Data Structures/Bogo Sort/Bogo_Sort.cpp
=> Bogo Sort Added using C++

Algorithms/max_sliding_window.cpp
=> Added Max Sliding Window in C++

C Language/Fibonacci Series
Fibonacci Series in C: In case of fibonacci series, next number is the sum of previous two numbers for example 0, 1, 1, 2, 3, 5, 8, 13, 21 etc. The first two numbers of fibonacci series are 0 and 1.
- [x ] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [ x] I have made corresponding changes to the documentation.
- [ x] My changes generate no new warnings.
- [ x] I have added tests that prove my fix is effective or that my feature works.
- [ x] New and existing unit tests pass locally with my changes.
- [ x] Any dependent changes have been merged and published in downstream modules.
=> Fibonacci Series

Algorithms/rotate_matrix.cpp
=> Rotate 2D matrix - C++

CP/4Sum.cpp
=> 4Sum LeetCode-18

CP/Majority Element II.cpp
=> Majority Element II LeetCode-229

Python/JS_Divergence.py
Added fucntion to calculate js divergence between two distributions.
Directory of new/updated file: "Python"
=> js divergence

Project/Python/passward.py
password generator using python
=> password generator

Algorithms/binary_exponentiation.cpp
=> Added Binary Exponentiation c++

Web development/ToDo-List/index.html, Web development/ToDo-List/script.js, Web development/ToDo-List/style.css
=> Created To-Do list using HTML, CSS, JAVASCRIPT

Data Structures/Tree/Tree Traversals/inorderTraversal.cpp, Data Structures/Tree/Tree Traversals/postorderTraversal.cpp, Data Structures/Tree/Tree Traversals/preorderTraversal.cpp
=> Tree Traversal

CP/Count_pairs_with_given_sum.cpp
=> count pairs with given sum

Algorithms/Dynamic Programming/LongestIncreasingSubsequence.cpp
=> Added the code for Longest Increasing Subsequence in C++

Cryptography Algorithms/MultiplicativeCipher.java
Implemented Multiplicative Cipher in java
<br>
Directory of new/updated file: "Cryptography Algorithms"
=> implemented Multiplicative cipher

Data Structures/Binary Trees/construct_tree_from_inorder_preorder.cpp
=> Construct Binary Tree from Inorder, Preorder

CP/combination_sum.cpp
=> Combination Sum C++

Algorithms/Morris_Inorder.cpp
Please accept for hacktoberfest 2022
=> Added code for Morris Inorder Traversal

Data Structures/HashMaps/Extract Unique Characters.java, Data Structures/HashMaps/Longest subset zero sum.java, Data Structures/HashMaps/pair sum to 0.java, README.md
I have created a new folder named "HashMaps" under the folder "Data Structures" and have added 3 programs under it. I have also updated the repository's ReadMe file to include the new directory and its contents in the tree structure.
Directory of new/updated file: "/Data Structures/HashMaps"
=> Added 3 Programs under Data Structures

CP/Factorials_of_large_numbers.cpp.txt
=> Factorials of large numbers

Data Structures/HashMaps/Pairs with difference K.java, Data Structures/Recursion/Return Keypad Code.java, README.md
Added one program each for HashMaps and Recursion respectively, and updated the readme accordingly.
1. HashMaps - Pairs with difference K.java
2. Recursion - Return Keypad Code.java
Directory of new/updated file: "/Data Structures/HashMaps", "/Data Structures/Recursion"
=> Added one program each for HashMaps and Recursion respectively, and updated the readme accordingly.

CP/Common_elements.cpp.txt
=> Common elements problem

C Language/binrec.c, C Language/fibrec.c, C Language/recursive.c, C Language/selectsort.c
=> Added my programs.

Data Structures/Recursion/binrec.c, Data Structures/Recursion/factrec.c, Data Structures/Recursion/fibrec.c, Data Structures/Recursion/recursive.c
<br>
Directory of new/updated file: "Recursion in C Programs"
- [x ] New feature (non-breaking change which adds functionality)
- [x ] I have performed a self-review of my own code.
- [x ] I have commented on my code, particularly in hard-to-understand areas.
- [ x] My changes generate no new warnings.
=> Contributed four recursion programs

Longest cycle in graph.cpp
=> longest cycle in graph

Algorithms/RabinKarpAlgorithm.cpp
=> Rabin Karp Algorithm

Data Structures/Chocolate_Distribution_Problem.cpp
=> Chocolate_Distribution_Problem.cpp

CONTRIBUTING.md
Modified the Contributing.md to define the type of issues / items we are looking fot
=> Modify `Contributing.md`

.github/PULL_REQUEST_TEMPLATE.md
Modified PR template to include documentation changes
=> Modify PR Template

.github/workflows/generate_project_tree_structure.yml, README.md
=> NOTICKET Fix Workflow

.github/workflows/generate_project_tree_structure.yml
=> [hacktoberfest] fix file name

.github/workflows/generate_project_tree_structure.yml
=> NOTICKET fix code block

.github/workflows/generate_project_tree_structure.yml, README.md
=> Remove Update Readme Action

CP/TopologicalSort/UsingDFS.cpp, CP/TopologicalSort/UsingKahnAlgo.cpp
Fixes #355 
/cp
/ ToplogicalSort
- Added Kahn Algo 
- Added DFS
=> Topological sort using Kahn Algo and DFS

Web development/PopUp Design/index.html, Web development/PopUp Design/style.css
Added a Pop Up Design made using basic html, css and javascript. 
Location : Web development/Popup Design
https://github.com/user-attachments/assets/786659f9-a334-4299-9a33-38ef64712286
=> feat: Popup Design Component

Java/fibonacci.java
Addition of fibonacci series in java
Fixes #344
=> Fibonacci series addition

Web development/BMI Calculator/app.js, Web development/BMI Calculator/index.html, Web development/BMI Calculator/styles.css
NEW FEATURES ADDED ( BMI can be calculated in inches and pounds now, the quantity can be reset and the category of bmi will also be displayed)
=> New features added.

Artificial Intelligence/Create Iterative Deepening Search.py
=> Create Iterative Deepening Search.py

CP/HamiltonianCycle.cpp
Hamiltonian Cycle problem using a backtracking approach
Hamiltonian Cycle problem using a backtracking approach
Fixes #371
=> added Hamiltonian Cycle problem

Java/BinarySearch.java
Add Java Binary Search snippet.
https://github.com/Kavya-24/Snippets/issues/400
My code follows the style guidelines of this project.
N/A
=> feat: added java binary search snippet

Competitive programming template/template.py
Create a competitve programming template in python
=> Create template.py for Competitve Programming
